intestsql: test: drop opt/, drop support of running outside ci_s3_integration

diff --git a/test/src/901-ingestsql/run_test b/test/src/901-ingestsql/run_test
--- a/test/src/901-ingestsql/run_test
+++ b/test/src/901-ingestsql/run_test
@@ -42,87 +42,92 @@ access_key = $CVMFS_S3_ACCESS_KEY
 secret_key = $CVMFS_S3_SECRET_KEY
 EOF
 else
-    S3_SERVER_PROVIDED=0
-    S3_HOST=127.0.0.1
-    S3_PORT=8000
-    S3_WEB_HOST=127.0.0.1
-    S3_WEB_PORT=8000
-    export CVMFS_TEST_HTTP_BASE=http://127.0.0.1:8000/"$CVMFS_TEST_REPO"
-    sudo mkdir -p /shared
-    CVMFS_TEST_S3_CONFIG=/shared/test_s3.conf
-    sudo tee "$CVMFS_TEST_S3_CONFIG" <<EOF
-CVMFS_S3_ACCESS_KEY=**UNUSED**
-CVMFS_S3_SECRET_KEY=**UNUSED**
-CVMFS_S3_HOST=$S3_HOST
-CVMFS_S3_PORT=$S3_PORT
-CVMFS_S3_REGION=auto
-CVMFS_S3_BUCKET=$CVMFS_TEST_REPO
-CVMFS_S3_X_AMZ_ACL=public-read
-CVMFS_S3_MAX_NUMBER_OF_PARALLEL_CONNECTIONS=64
-CVMFS_S3_DNS_BUCKETS=false
-CVMFS_S3_URI_SCHEME=http
-CVMFS_S3_PROXY=http://127.0.0.1:8088
-CVMFS_S3_MAX_RETRIES=1000
-EOF
-    source "$CVMFS_TEST_S3_CONFIG"
-    export CVMFS_TEST_S3_CONFIG # for graft-tests.py
-
-    sudo mkdir -p /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"
-    sudo touch             /var/log/small-proxyd.log /var/log/small-httpd.log /var/log/gateway.log
-    sudo chown "$(whoami)" /var/log/small-proxyd.log /var/log/small-httpd.log /var/log/gateway.log
-    ! sudo fuser -n tcp 8088
-    sudo stdbuf -i0 -o0 -e0  "$this_script_dir"/opt/bin/proxy_server.py     |& sudo tee /var/log/small-proxyd.log &
-    ! sudo fuser -n tcp 8000
-    sudo stdbuf -i0 -o0 -e0  "$this_script_dir"/opt/bin/http_server.py 8000 |& sudo tee /var/log/small-httpd.log  &
-    for seconds in {1..10}; do
-        if http_ports_up; then break; fi
-        sleep 1
-    done
-    http_ports_up
+    false
+#    S3_SERVER_PROVIDED=0
+#    S3_HOST=127.0.0.1
+#    S3_PORT=8000
+#    S3_WEB_HOST=127.0.0.1
+#    S3_WEB_PORT=8000
+#    export CVMFS_TEST_HTTP_BASE=http://127.0.0.1:8000/"$CVMFS_TEST_REPO"
+#    sudo mkdir -p /shared
+#    CVMFS_TEST_S3_CONFIG=/shared/test_s3.conf
+#    sudo tee "$CVMFS_TEST_S3_CONFIG" <<EOF
+#CVMFS_S3_ACCESS_KEY=**UNUSED**
+#CVMFS_S3_SECRET_KEY=**UNUSED**
+#CVMFS_S3_HOST=$S3_HOST
+#CVMFS_S3_PORT=$S3_PORT
+#CVMFS_S3_REGION=auto
+#CVMFS_S3_BUCKET=$CVMFS_TEST_REPO
+#CVMFS_S3_X_AMZ_ACL=public-read
+#CVMFS_S3_MAX_NUMBER_OF_PARALLEL_CONNECTIONS=64
+#CVMFS_S3_DNS_BUCKETS=false
+#CVMFS_S3_URI_SCHEME=http
+#CVMFS_S3_PROXY=http://127.0.0.1:8088
+#CVMFS_S3_MAX_RETRIES=1000
+#EOF
+#    source "$CVMFS_TEST_S3_CONFIG"
+#    export CVMFS_TEST_S3_CONFIG # for graft-tests.py
+#
+#    sudo mkdir -p /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"
+#    sudo touch             /var/log/small-proxyd.log /var/log/small-httpd.log /var/log/gateway.log
+#    sudo chown "$(whoami)" /var/log/small-proxyd.log /var/log/small-httpd.log /var/log/gateway.log
+#    ! sudo fuser -n tcp 8088
+#    sudo stdbuf -i0 -o0 -e0  "$this_script_dir"/opt/bin/proxy_server.py     |& sudo tee /var/log/small-proxyd.log &
+#    ! sudo fuser -n tcp 8000
+#    sudo stdbuf -i0 -o0 -e0  "$this_script_dir"/opt/bin/http_server.py 8000 |& sudo tee /var/log/small-httpd.log  &
+#    for seconds in {1..10}; do
+#        if http_ports_up; then break; fi
+#        sleep 1
+#    done
+#    http_ports_up
 fi
 
-gateway_up() {
-    sudo fuser -n tcp 4929
-}
-GW_SHOULD_RESTART_FILE=$(mktemp --suffix=.gw-should-restart.901-ingestsql.XXXXXXX)
-run_gateway() {
-    while [[ -f "$GW_SHOULD_RESTART_FILE" ]]; do
-        MAYBE_TRACER=''
-        RECEIVER=$(which cvmfs_receiver)
-        if [[ -v DEBUG ]]; then
-            MAYBE_TRACER=rr
-            RECEIVER="$this_script_dir/receiver-wrapper"
-        fi
-        sudo $MAYBE_TRACER cvmfs_gateway --access_config_file /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/repo.json --user_config_file /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/user.json --work_dir /var/lib/cvmfs-gateway/"$CVMFS_TEST_REPO" --receiver_path "$RECEIVER" |& sudo tee -a /var/log/gateway.log
-    done &
-    for seconds in {1..10}; do
-	if gateway_up; then break; fi
-	sleep 1
-    done
-    trap stop_gateway ERR
-}
-stop_gateway() {
-    rm "$GW_SHOULD_RESTART_FILE" || true
-    sudo killall cvmfs_gateway || true
-    while sudo pgrep cvmfs_gateway; do
-	sleep 0.1
-    done
-    ! gateway_up
-    trap - ERR
-}
+# gateway_up() {
+#     sudo fuser -n tcp 4929
+# }
+# GW_SHOULD_RESTART_FILE=$(mktemp --suffix=.gw-should-restart.901-ingestsql.XXXXXXX)
+# run_gateway() {
+#     while [[ -f "$GW_SHOULD_RESTART_FILE" ]]; do
+#         MAYBE_TRACER=''
+#         RECEIVER=$(which cvmfs_receiver)
+#         if [[ -v DEBUG ]]; then
+#             MAYBE_TRACER=rr
+#             RECEIVER="$this_script_dir/receiver-wrapper"
+#         fi
+#         sudo $MAYBE_TRACER cvmfs_gateway --access_config_file /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/repo.json --user_config_file /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/user.json --work_dir /var/lib/cvmfs-gateway/"$CVMFS_TEST_REPO" --receiver_path "$RECEIVER" |& sudo tee -a /var/log/gateway.log
+#     done &
+#     for seconds in {1..10}; do
+# 	if gateway_up; then break; fi
+# 	sleep 1
+#     done
+#     trap stop_gateway ERR
+# }
+# stop_gateway() {
+#     rm "$GW_SHOULD_RESTART_FILE" || true
+#     sudo killall cvmfs_gateway || true
+#     while sudo pgrep cvmfs_gateway; do
+# 	sleep 0.1
+#     done
+#     ! gateway_up
+#     trap - ERR
+# }
 
-sudo rsync -rtv "$this_script_dir"/etc/cvmfs/gateway  /etc/cvmfs
-sed "$this_script_dir"/etc/cvmfs/gateway/test.repo/repo.json.in \
-    -e "s#\$CVMFS_TEST_HTTP_BASE#$CVMFS_TEST_HTTP_BASE#" \
-    -e "s#\$CVMFS_TEST_REPO#$CVMFS_TEST_REPO#" \
-| sudo tee /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/repo.json
+(
+    source "$TEST_ROOT"/test_functions
+    set_up_repository_gateway "$CVMFS_TEST_REPO" -o "$CVMFS_TEST_USER" -w "$CVMFS_TEST_HTTP_BASE" -s "$CVMFS_TEST_S3_CONFIG"
+)
+#sudo rsync -rtv "$this_script_dir"/etc/cvmfs/gateway  /etc/cvmfs
+#sed "$this_script_dir"/etc/cvmfs/gateway/test.repo/repo.json.in \
+#    -e "s#\$CVMFS_TEST_HTTP_BASE#$CVMFS_TEST_HTTP_BASE#" \
+#    -e "s#\$CVMFS_TEST_REPO#$CVMFS_TEST_REPO#" \
+#| sudo tee /etc/cvmfs/gateway/"$CVMFS_TEST_REPO"/repo.json
 
 sudo rsync -rtv "$this_script_dir"/etc/cvmfs/config.d /etc/cvmfs
-sudo rsync -rtv "$this_script_dir"/etc/cvmfs-gateway-client  /etc
-! gateway_up
-touch "$GW_SHOULD_RESTART_FILE"
-run_gateway
-gateway_up
+#sudo rsync -rtv "$this_script_dir"/etc/cvmfs-gateway-client  /etc
+#! gateway_up
+#touch "$GW_SHOULD_RESTART_FILE"
+#run_gateway
+#gateway_up
 
 
 if ! grep '^user_allow_other' /etc/fuse.conf; then
@@ -139,7 +144,7 @@ if [[ -v RECONSTRUCT_REPO ]]; then
         apache_switch on
     )
 
-    sudo cvmfs_server mkfs -o "$CVMFS_TEST_USER" -w "$CVMFS_TEST_HTTP_BASE" -s "$CVMFS_TEST_S3_CONFIG" "$CVMFS_TEST_REPO"
+    #sudo cvmfs_server mkfs -o "$CVMFS_TEST_USER" -w "$CVMFS_TEST_HTTP_BASE" -s "$CVMFS_TEST_S3_CONFIG" "$CVMFS_TEST_REPO"
     sudo cp /etc/cvmfs/keys/"$CVMFS_TEST_REPO".pub /etc/cvmfs-gateway-client/"$CVMFS_TEST_REPO"/pubkey
 
     sudo cvmfs_server transaction "$MY_REPO"
@@ -157,8 +162,8 @@ else # ! [[ -v RECONSTRUCT_REPO ]]
     sudo touch /etc/fstab # absense of /etc/fstab on CentOS 9 containers breaks `cvmfs_server migrate`
     sudo mkdir -p /var/spool/cvmfs/"$CVMFS_TEST_REPO"
     sudo rsync -rtv "$this_script_dir"/var/spool/cvmfs/test.repo/{reflog.chksum,tmp}  /var/spool/cvmfs/"$CVMFS_TEST_REPO"
-    sudo mkdir -p /var/http/root/"$CVMFS_TEST_REPO"/
-    sudo rsync -rtv "$this_script_dir"/var/http/root/test.repo/test.repo/  /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"
+    #sudo mkdir -p /var/http/root/"$CVMFS_TEST_REPO"/
+    #sudo rsync -rtv "$this_script_dir"/var/http/root/test.repo/test.repo/  /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"
     if [[ "$S3_SERVER_PROVIDED" == 1 ]]; then
         pushd "$this_script_dir"/var/http/root/test.repo/
         find test.repo/ -type f -print0 | xargs --verbose -0 -I '{}' s3cmd put '{}' s3://"$CVMFS_S3_BUCKET"/'{}'
@@ -188,9 +193,9 @@ fi
 sudo mkdir -p "$CVMFS_TEST_MOUNTPOINT"
 # TODO The manifest file .cvmfspublished file contains test.repo as repo name, needs changing and re-signing for parametrized $CVMFS_TEST_REPO.
 # Check that HTTP servers serve expected contents:
-diff -Nurd /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"/.cvmfspublished <(curl --disable --verbose --fail "$CVMFS_TEST_HTTP_BASE"/$CVMFS_TEST_REPO/.cvmfspublished)
+diff -Nurd "$this_script_dir"/var/http/root/test.repo/"$CVMFS_TEST_REPO"/.cvmfspublished <(curl --disable --verbose --fail "$CVMFS_TEST_HTTP_BASE"/$CVMFS_TEST_REPO/.cvmfspublished)
 if [[ "$S3_SERVER_PROVIDED" == 0 ]]; then
-    diff -Nurd /var/http/root/"$CVMFS_TEST_REPO"/"$CVMFS_TEST_REPO"/.cvmfspublished <(curl --disable --verbose --fail --proxy http://localhost:8088 "$CVMFS_TEST_HTTP_BASE"/$CVMFS_TEST_REPO/.cvmfspublished)
+    diff -Nurd "$this_script_dir"/var/http/root/test.repo/"$CVMFS_TEST_REPO"/.cvmfspublished <(curl --disable --verbose --fail --proxy http://localhost:8088 "$CVMFS_TEST_HTTP_BASE"/$CVMFS_TEST_REPO/.cvmfspublished)
 fi
 
 sudo "$CVMFS2" -d -o config=/etc/cvmfs/repositories.d/$CVMFS_TEST_REPO/client.conf,allow_other $CVMFS_TEST_REPO "$CVMFS_TEST_MOUNTPOINT" |& sudo tee -a /var/log/cvmfs2.log
@@ -208,5 +213,3 @@ export PYTHONIOENCODING=UTF-8
 export LANG=C.UTF-8
 
 sudo -E "$this_script_dir"/graft-tests.py --no-mount standard |& sudo tee /var/log/graft-tests.log
-
-stop_gateway
